### ISSUE TITLE
September 15 discussion

### ISSUE THREAD

**Issue by jadeallenx** [gootik/this-week-in-erlang#12]
Please comment here if you wish to add or suggest something to include in the next newsletter.

**Comment by jadeallenx** [comment]
Property based testing website: http://propertesting.com/ by @ferd

**Comment by jadeallenx** [comment]
@kaos, one of the maintainers of [erlyDTL](https://github.com/erlydtl/erlydtl) is looking for someone to take over maintainership of the library.

**Comment by marianoguerra** [comment]
exometer_core 1.5.0 released https://github.com/Feuerlabs/exometer_core/tree/1.5.0

**Comment by marianoguerra** [comment]
meck moved to test profile and edoc to test profile \o/ https://github.com/Feuerlabs/exometer_core/commit/c4afd6d095c8eef7c5447133a033b9165f53da02#diff-31d7a50c99c265ca2793c20961b60979R20

**Comment by marianoguerra** [comment]
reminder of the survey: http://bit.ly/state-of-beam-2017

**Comment by marianoguerra** [comment]
the discussion on the erlang mailing list about migrating it to rust http://erlang.org/pipermail/erlang-questions/2017-September/093330.html

**Comment by marianoguerra** [comment]
Investigating Erlang by reading its system calls

https://jvns.ca/blog/2016/05/13/erlang-seems-really-complicated/

**Comment by jadeallenx** [comment]
Just merged #13
