### ISSUE TITLE
Discussion for September 22

### ISSUE THREAD

**Issue by jadeallenx** [gootik/this-week-in-erlang#14]
Please comment here if you have any suggestions for the September 22 issue of the newsletter. Thanks.

**Comment by jadeallenx** [comment]
https://medium.com/tech-lead-talks/the-best-company-i-ever-worked-for-1088d9ab3609

**Comment by marianoguerra** [comment]
Multi-Paxos with riak_ensemble Part 2

http://marianoguerra.org/posts/multi-paxos-with-riak_ensemble-part-2/

**Comment by jadeallenx** [comment]
Understanding BEAM op codes: http://beam-wisdoms.clau.se/en/latest/

**Comment by jadeallenx** [comment]
Interesting RPC framework: https://github.com/g-andrade/backwater

**Comment by jadeallenx** [comment]
Why is this variable unbound?

https://stackoverflow.com/questions/46377003/when-pattern-matching-maps-in-erlang-why-is-this-variable-unbound?noredirect=1#comment79716313_46377003

**Comment by jadeallenx** [comment]
Non-blocking code loading: https://github.com/erlang/otp/blob/master/erts/emulator/internal_doc/CodeLoading.md

**Comment by jadeallenx** [comment]
First ever Elixir and Erlang Factory Light in Bangalore: http://www.erlang-factory.com/india2017/
