### ISSUE TITLE
Discussion for Oct 1

### ISSUE THREAD

**Issue by jadeallenx** [gootik/this-week-in-erlang#16]
This issue is for discussion around items to include in the September 29 newsletter.  Please leave a comment if you have a suggestion for inclusion in the newsletter.

**Comment by jadeallenx** [comment]
RabbitMQ is moving toward Github, Bintray and CDNs for binary releases.

https://groups.google.com/forum/#!topic/rabbitmq-users/9ASVq55wXnA

**Comment by gootik** [comment]
RabbitMQ book by Gavin M. Roy `@crad`
https://www.manning.com/books/rabbitmq-in-depth

**Comment by gootik** [comment]
https://sbcnews.co.uk/features/2017/09/26/erlang-elixir-programming-language/amp/

**Comment by marianoguerra** [comment]
Multi-Paxos with riak_ensemble Part 3

http://marianoguerra.org/posts/multi-paxos-with-riak_ensemble-part-3/

**Comment by marianoguerra** [comment]
hinterface - Haskell / Erlang interoperability library

Inspired by Jinterface (Java), a set of tools for communication with Erlang processes.

https://github.com/lindenbaum/hinterface

**Comment by marianoguerra** [comment]
Erlang 20.1 released

http://www.erlang.org/news/115
https://github.com/erlang/otp/releases/tag/OTP-20.1

**Comment by marianoguerra** [comment]
Data efficiency on the BEAM by Dmytro Lytovchenko/Erlang Solutions
https://www.youtube.com/watch?v=_QUVpYXuR80&feature=youtu.be

**Comment by marianoguerra** [comment]
Call Me… Maybe?

https://medium.com/erlang-battleground/call-me-maybe-28671e6b92f4

**Comment by marianoguerra** [comment]
Go, Erlang, Elixir; what’s in a programming language anyway?

https://sbcnews.co.uk/features/2017/09/26/erlang-elixir-programming-language/

**Comment by marianoguerra** [comment]
Job search for Erlang/Rust by Helium

https://angel.co/helium-2/jobs/281695-software-engineer

**Comment by jadeallenx** [comment]
Implementation of Erlang/OTP node in Go: https://github.com/halturin/ergonode

**Comment by jadeallenx** [comment]
Interesting PR on OTP to allow upgrade to a new version without a relup or restarting the VM: https://github.com/erlang/otp/pull/1581

**Comment by gootik** [comment]
This whole thread/discussion started by Joe: https://twitter.com/joeerl/status/911646823248523265

This library by @clanchun https://github.com/clanchun/epipe
and another by @ferd https://github.com/ferd/fancyflow
