### ISSUE TITLE
Discussion for Oct 6

### ISSUE THREAD

**Issue by gootik** [gootik/this-week-in-erlang#18]
Things we want to include in the newsletter. Don't forget the suggtions that didn't make last week, marked as 🎉 : https://github.com/gootik/this-week-in-erlang/issues/16

**Comment by jadeallenx** [comment]
Using kerl to compile older Erlangs on High Sierra (macOS 10.13) has problems relating to the definition inside of Erlang's autoconf configuration. You can follow the progress here: https://github.com/kerl/kerl/pull/230

**Comment by jadeallenx** [comment]
The PR to move ERTS IO polling to their own threads was merged. https://github.com/erlang/otp/pull/1552

**Comment by gootik** [comment]
NHS and Riak https://www.youtube.com/watch?v=WFghXj5Bus8

**Comment by gootik** [comment]
BEAM implementation in Rust from @kvakvs https://github.com/kvakvs/ErlangRT

**Comment by gootik** [comment]
Unsing Ansible to create BEAM Virtual Machine http://opensourceforu.com/2017/10/developing-virtual-machine-erlangotp-using-ansible/

**Comment by gootik** [comment]
Cowboy 2.0 released https://ninenines.eu/articles/cowboy-2.0.0/

**Comment by jadeallenx** [comment]
Interesting back and forth about McErlang, QuickCheck/PULSE and Concuerror on this Erlang Questions thread. 

http://erlang.org/pipermail/erlang-questions/2017-October/093782.html

This is the last post so far.

**Comment by gootik** [comment]
"Using ErlangPL on a real project" by @mkacper https://medium.com/@mentel.kk/using-erlang-performance-lab-with-a-real-project-f101f39619c7

**Comment by gootik** [comment]
This tweet :D https://twitter.com/jlouis666/status/916021955454799873
