### ISSUE TITLE
August 11 Conversation

### ISSUE THREAD

**Issue by marianoguerra** [gootik/this-week-in-erlang#2]
is it ok to open an issue per week to have a conversation and have sugestions?

it's much more approachable than a PR.

we can use this for next week's edition.

my comments:

libs: worker_pool, recon

projects: https://bragful.com/en

**Comment by gootik** [comment]
Yeah sounds good!

**Comment by gootik** [comment]
`jobs` by Ulf was released to hex https://github.com/uwiger/jobs

**Comment by gootik** [comment]
Presentation https://media.ccc.de/v/SHA2017-304-introducing_talla_an_erlang_implementation_of_tor

**Comment by gootik** [comment]
Article https://potatosalad.io/2017/08/05/latency-of-native-functions-for-erlang-and-elixir.html

**Comment by gootik** [comment]
News https://www.erlang-solutions.com/blog/riak-commercial-support-now-available-post-basho.html
