### ISSUE TITLE
Oct 13 discussion

### ISSUE THREAD

**Issue by gootik** [gootik/this-week-in-erlang#20]

**Comment by gootik** [comment]
Suggested by mononcqc https://github.com/jlouis/eministat

**Comment by jchassoul** [comment]
https://luerl.org https://github.com/rvirding/luerl (= multiple merge's from hex pkg, get started tutorial, lua sandboxing examples and little progressive improvements on docs from different contributors this week!

**Comment by gootik** [comment]
http://marcelog.github.io/articles/erlang_tutorial_for_php_developers.html

**Comment by gootik** [comment]
https://medium.com/erlang-battleground/erlang-behaviors-4348e89351ff

**Comment by areegea** [comment]
Can we add CodeMesh 2017 in London to the events section? Early bird closes 17 October, group discounts available. http://www.codemesh.io/#home Thanks!

**Comment by gootik** [comment]
@areegea of course.

**Comment by marianoguerra** [comment]
https://holidayping.lambdaclass.com/

a project whose backend is erlang and frontend in clojurescript and it's open source

https://github.com/lambdaclass/holiday_ping

**Comment by marianoguerra** [comment]
epgsql 3.4.0 released:

https://github.com/epgsql/epgsql/releases/tag/3.4.0



* Use rebar3 as default build and test tool
* Move tests to common test; launch test postgresql server from Erlang
* Compatibility with Erlang 20
* ssl_options connection option fixed
* New types: int8range and int4range
