### ISSUE TITLE
Oct 27th

### ISSUE THREAD

**Issue by gootik** [gootik/this-week-in-erlang#24]
What to include?

**Comment by gootik** [comment]
https://github.com/ninenines/cowboy/compare/d43bcb5cb3...4211ea41bd

**Comment by jadeallenx** [comment]
Lager had a minor bugfix release on Thursday that merged a PR which fixes a long-standing Unicode handling bug. https://github.com/erlang-lager/lager#3x-changelog

**Comment by jadeallenx** [comment]
Pretty interesting project [announced on erlang-questions][1] called [fez][2] which translates F# to core erlang and runs on BEAM.


[1]: http://erlang.org/pipermail/erlang-questions/2017-October/093934.html
[2]: https://github.com/kjnilsson/fez

**Comment by fenollp** [comment]
Kinda tooting my own horn: @uwiger merged my patch to support maps in ct_expand:term/1
meaning fixtures (such as JSON schemas) can be turned into constants at compile time.

merged PR: https://github.com/uwiger/parse_trans/pull/24
Latest hex: https://hex.pm/packages/parse_trans/3.1.0

People probably don't know about ct_expand and while it will make compile times longer it can be of great use.

**Comment by gootik** [comment]
https://github.com/rabbitmq/looking_glass/blob/master/doc/src/guide/flame.asciidoc

**Comment by gootik** [comment]
http://blog.hellkvist.org/2017/10/26/the-joy-of-pattern-matching-part-ii/

**Comment by gootik** [comment]
https://www.stackpair.com/expa/san-francisco/blockchain-tech-lead

**Comment by gootik** [comment]
https://medium.com/erlang-battleground/advanced-list-incomprehensions-6957863dfb4f

**Comment by jadeallenx** [comment]
https://github.com/erlang/otp/pull/1602

A refactored/modernized supervisor is coming!

**Comment by getong** [comment]
erlang otp 20.1.6 released.
cowboy 2.1.0 released.
couchdb 2.1.1 released.
MongooseIM 2.1.0 released.
[RIAK WORKSHOP SUMMARY](http://bet365techblog.com/riak-workshop-summary)
erlang/otp#1635
rabbitmq-server 3.7.0 rc2 release, GA is very soon

**Comment by fenollp** [comment]
Just discovered https://github.com/esl/Pyrlang even though it looks like it's 2 months old

**Comment by crownedgrouse** [comment]
is TWIE dead ? nothing since Oct 20th ?

**Comment by gootik** [comment]
@crownedgrouse I was really busy for a while and wasn't able to publish. I will get back on track this week though :)

**Comment by crownedgrouse** [comment]
great.  maybe could we call this next upcoming news "This Month in Erlang" ? :>)

**Comment by gootik** [comment]
Thanks everyone for the comments and help. I just did a very small post. will keep this open and add items from here for the next one.

**Comment by jadeallenx** [comment]
I can help chip in from time to time - maybe we should recruit some more editors so the release cadence is more regular and less dependent on @gootik directly.

**Comment by gootik** [comment]
@mrallen1 I agree, the more help we have the better. if anyone opens a PR then it's easy to merge and publish.

**Comment by getong** [comment]
rabbitmq 3.7.0 release

**Comment by jadeallenx** [comment]
https://github.com/erlang/eep/blob/master/eeps/eep-0047.md

**Comment by jadeallenx** [comment]
https://medium.com/@ErlangSolutions/erlang-garbage-collector-dfc9ad952130
