### ISSUE TITLE
Don't learn Erlang

### ISSUE THREAD

**Issue by gootik** [gootik/this-week-in-erlang#48]
### DATE (yyyy/mm/dd)
2018/04/06

### CATEGORY (article/library update/announcement/OTP/employment/event)
article

### DESCRIPTION
While this is not the best piece of news out there about Erlang, the community should still be aware of the problems and try to solve them if possible. This article does a quantitative analysis of why learning Erlang in 2018 is not a good idea.

### LINK
https://www.codementor.io/blog/worst-languages-to-learn-3phycr98zk?utm_content=67871817&utm_medium=social&utm_source=twitter

**Comment by jadeallenx** [comment]
omg I hate articles like this  I heard the same thing about perl and ruby for YEARS. So irritating. 😝

**Comment by OvermindDL1** [comment]
_/me still has to use perl on old systems at work... Ruby can diaf though  ^.^;_

**Comment by jadeallenx** [comment]
Heh
