### ISSUE TITLE
Sep 1st Discussion

### ISSUE THREAD

**Issue by marianoguerra** [gootik/this-week-in-erlang#8]
Today (25th of august) an online meeting was held to discuss the future of riak, this document was available online: https://slack-files.com/T6PE2GNC8-F6U0FEFKP-b5db1a9fcd

the meeting is still ongoing check https://twitter.com/bytemeorg for updates

**Comment by gootik** [comment]
ty

**Comment by gootik** [comment]
rocksdb-erlang release https://gitlab.com/barrel-db/erlang-rocksdb/blob/master/CHANGELOG

**Comment by gootik** [comment]
OTP 20 & 19 `rand` module article http://erlang.org/pipermail/erlang-questions/2017-August/093148.html

**Comment by gootik** [comment]
Ferd on safe SSL https://gist.github.com/ferd/af9abf6b3600d2d7f08dba58fdfb514a

**Comment by marianoguerra** [comment]
Multi-Paxos with riak_ensemble Part 1 http://marianoguerra.org/posts/multi-paxos-with-riak_ensemble-part-1/

**Comment by marianoguerra** [comment]
Would you announce the start of the "State of the BEAM survey" tomorrow?

here's the link to the survey: http://bit.ly/state-of-beam-2017

the text can be something like "We want to make the BEAM community better, for that we need to know who we are, what we do, what we like and what we don't like. Today we are launching the first in what hopefully becomes a yearly survey on the State of the BEAM, please fill the survey and share it widely so we get a good representation of the community"

(feel free to improve it)

**Comment by gootik** [comment]
Yes, of course.
